# Generated by Django 3.0.8 on 2020-07-20 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeviceData',
            new_name='Device_Data',
        ),
    ]
