# Generated by Django 3.0.8 on 2020-07-20 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0002_auto_20200720_1153'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Device_Data',
        ),
    ]
