# Generated by Django 3.0.8 on 2020-07-20 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_delete_device_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('power', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='功率')),
                ('created_time', models.DateTimeField(verbose_name='生成时间')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data', to='server.Device', verbose_name='设备')),
            ],
            options={
                'verbose_name': '数据',
                'verbose_name_plural': '数据',
            },
        ),
    ]
