# Generated by Django 3.0.8 on 2020-07-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_device_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='id',
        ),
        migrations.AlterField(
            model_name='device',
            name='deviceID',
            field=models.CharField(max_length=16, primary_key=True, serialize=False, verbose_name='设备ID'),
        ),
        migrations.AlterField(
            model_name='device_data',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='生成时间'),
        ),
    ]
